### ISSUE TITLE
Is it possible to use this with Custom Database.

### ISSUE THREAD

**Issue by fizmhd** [hernandgr/AspNetIdentityDemo#1]
Sorry first of this is not an issue, I am new to mvc and I want to implement a login, 
Your solution looks very neat and simple, and I was going through the code,  I couldnt find a place where the username and details are stored, so I was wondering is it possible to save it to my custom db

Please let me know. 
Thanks.

**Comment by hernandgr** [comment]
Hi @fizmhd. 

This is a very basic and empty example. The classes in **AuthenticationTest.Services** project are intented to do the storage operations. So, this is the place where you could have the access to your custom database.

Hope it can help you!

**Comment by fizmhd** [comment]
@hernandgr Thanks.
